Tell the user what to do to fix it. Prettier on unformatted files

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -42,4 +42,4 @@ jobs:
         run: pnpm manypkg check
 
       - name: Check formatting with Prettier
-        run: pnpm prettier
+        run: pnpm prettier || (echo "::error::Formatting issues detected! Run 'pnpm prettier:fix' to fix them" && exit 1)
